### ISSUE TITLE
Update to Dawn version 6.0.2?

### ISSUE THREAD

**Issue by shaunbrazier** [TrellisCommerce/shopify-dawn-tailwind-starter-base#3]
Hi there,

I stumbled upon your repo - thank you for making this tailwind integration with Dawn available to us all. I just wanted to check if there are any plans to update the TrellisCommerce/shopify-dawn-tailwind-starter-base with the recent changes Shopify has made to Dawn, releasing version 6. These changes add several improvements, such as the ability to switch the cart functionality to a drawer. 

It would be great to know if this repo will follow suit?

Thanks again for the effort you've put into this thus far.

**Comment by MonarchOfSouls** [comment]
I think you can easily pull these changes by setting the upstream to the original dawn repo and thus pull the latest Version

"Before beginning any work, it is good practice to pull down the latest changes from the Shopify Dawn theme: `git fetch upstream git pull upstream main`

Add upstream link if you get the error fatal: 'upstream' does not appear to be a git repository run: git remote add upstream https://github.com/Shopify/dawn.git or git remote add upstream https://github.com/TrellisCommerce/shopify-dawn-tailwind-starter-base depending on which repository you want to pull updates from"

**Comment by cmegalo** [comment]
@shaunbrazier @MonarchOfSouls I went ahead and pulled in the latest Dawn repo changes. Should be good to go!
